spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/Product
    username: postgres
    password: 1
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true
server:
  port: 8080

upload:
  server:
    folder: D:/uploadFolderPath
